Feature timeline
ntpusu/ntpusu-vote pull request #70
Opened 2024-05-05 06:17 UTC by TonyLiu0430

2024-05-11 13:59 UTC, garyellow requested changes

2024-05-11 13:59 UTC, garyellow commented on pages/admin/editTimeline.vue
> +import { ref } from "vue";
這個應該有 [auto import](https://nuxt.com/docs/guide/concepts/auto-imports) 了

2024-05-11 13:59 UTC, garyellow commented on pages/admin/editTimeline.vue
> +const deleteActivity = async (id: number) => {
看起來不用 async
或是 $fetch 要加 await (建議這樣改)

2024-05-11 13:59 UTC, garyellow commented on pages/admin/editTimeline.vue
> +const editActivity = async (id: number) => {
ditto

2024-05-11 13:59 UTC, garyellow commented on pages/admin/editTimeline.vue
> +const editActivityId: Ref<number | null> = ref(null);
應該可以整理成一個 `reactive<Activity>` 
element plus 的 [form](https://element-plus.org/en-US/component/form.html#basic-form) 有範例

2024-05-11 13:59 UTC, garyellow commented on pages/admin/editTimeline.vue
> +const updateActivity = async (id: number) => {
ditto

2024-05-11 13:59 UTC, garyellow commented on pages/admin/editTimeline.vue
> +};
useFetch 有一個 transform 參數，應該可以做預處理([params](https://nuxt.com/docs/api/composables/use-fetch#params)、[example](https://nuxt.com/docs/getting-started/data-fetching#minimize-payload-size))
可以研究看看，不然現在的看起來挺複雜XD

2024-05-11 13:59 UTC, garyellow commented on pages/index.vue
> +};
ditto

2024-05-11 13:59 UTC, garyellow commented on server/api/timeline/add.put.ts
> +        }
可以加 `select: null`
減少資料庫做的事

2024-05-11 13:59 UTC, garyellow commented on server/api/timeline/add.put.ts
> +    }
讀完要確認 資料是否存在、格式數值正不正確

2024-05-11 13:59 UTC, garyellow commented on server/api/timeline/update.put.ts
> +    }
ditto

2024-05-11 13:59 UTC, garyellow commented on server/api/timeline/update.put.ts
> +        }
ditto `select: null`

2024-05-13 08:08 UTC, TonyLiu0430 commented on server/api/timeline/add.put.ts
> +        }
好像select null 會把所有資料都丟回來 https://github.com/prisma/prisma/issues/4246，好像只能指定一個欄位讓他只丟一個

2024-05-13 08:24 UTC, garyellow commented on server/api/timeline/add.put.ts
> +        }
對欸可能改了或之前抄到不好的code
之後再把 select: null 拔掉好了
或是看有沒有正確的寫法(可能空的大掛號之類的)

2025-04-22 07:44 UTC, TonyLiu0430 commented
lgtm

2025-04-22 07:50 UTC, merged